stages:
  - compile
  - test

include:
  - gitlab-runner/bionic-runner.yml
  - gitlab-runner/macos-runner.yml

.load-linux:
  variables:
    PYTHONPATH: ${CI_PROJECT_DIR}
  before_script:
    - export PATH=$PATH:/home/kovalp/programs/siesta/siesta-4.0.2/Obj
