#!/bin/sh 
#-------------------------------------------------------------
# Makes (compiles) the SIESTA program.
# Syntax:  msiesta [init|touch]
#
# If the 'init' option is specified, the default .h parameter files
# in SIESTA_DIR/Include are used (good for first compilation).
#
# If the 'touch' option is specified, the .h parameter files
# located in the working (project) directory are 'touched' and copied
# to the source directory. In this way the parameter information garnered
# in previous compilations can be reused even if other, unrelated, 
# compilation cycles have 'corrupted' the source directory.
#
# The environment variable $SIESTA_DIR, containing the path to the
# SIESTA source directory, should be previously defined.
# If it is not defined, it assumes SIESTA_DIR = ../siesta/Src
#
# The environment variable $ARCH should be previously defined,
#
# Written by J.M.Soler. Aug. 1997, Feb. 1998.
# Modified by :
#    Alberto Garcia, March 1998.
#    Emilio Artacho, March 1999.
#    Alberto Garcia, April 1999.
#-------------------------------------------------------------

if [ -z "$SIESTA_SYS" ] ; then
      echo "msiesta: You must set the environment variable \$SIESTA_SYS first"
      exit
fi
#
SIESTA_DIR=${SIESTA_DIR:=../siesta/Src}

WDIR=`pwd`

if [ $# -gt 1 ] ; then
      echo "msiesta: Usage: msiesta [init|touch]"
      exit
fi

if [ $# -eq 1 -a "$1" = "init" ] ; then
#
#  Use default .h files (and copy them to project directory)
#  Note that 'atom.h' does not usually need to be changed. Hence the
#  '-p' option to retain the datestamp.
#
  cp $SIESTA_DIR/Include/*.h $SIESTA_DIR
  cp -p $SIESTA_DIR/Include/atom.h $SIESTA_DIR
  cp $SIESTA_DIR/Include/constr.f $SIESTA_DIR
  cp $SIESTA_DIR/Include/*.h $WDIR
  cp -p $SIESTA_DIR/Include/atom.h $WDIR
#
else

  if [ $# -eq 1 -a "$1" = "touch" ] ; then
#
#     Re-use .h files from previous compilations in this directory
#
      touch siesta.h
      touch dhscf.h
      touch diagon.h
      touch diagnc.h
      touch matel.h
      touch ranger.h
      touch ordern.h
      if  [ -f constr.f ] ; then
         touch constr.f
      fi
  fi
#
# (If not 'init') Move .h files in project directory to source directory
#
  cp -p *.h $SIESTA_DIR   2>/dev/null
  if  [ -f $WDIR/constr.f ] ; then
      cp -p $WDIR/constr.f $SIESTA_DIR
  fi
fi
#
#  Ready to 'make' siesta
#
cd $SIESTA_DIR
make
if [ $? -eq 0 ] ; then
#
#       successful compilation; copy the executable to the project directory.
#
	mv siesta $WDIR
else
	echo "msiesta: make failed"
	exit 1
fi








