#!/bin/sh
#-------------------------------------------------------------
# Queues (submits) a job to run the SIESTA program, recompiling
# if necessary.
#
# Syntax:  qrrsiesta name queue [init]
# Example: qrrsiesta H2O express 
#
# Final SIESTA output goes to name.out. 
# A detailed log of the whole cycle goes to name.qlog.
#
# Environment variable $SIESTA_DIR should be previously defined.
# If it is not defined, it assumes SIESTA_DIR = ../Src
#
# Environment variable $SIESTA_BIN can be defined to locate
# the utility scripts called by this one.
# If it is not defined, it assumes SIESTA_BIN = ../Util
#
# Data file name.fdf must exist in working directory.
# rrsiesta et al must be in user's path.
# Written by J.M.Soler. August 1997.
# Modified by Alberto Garcia, March 1998.
#-------------------------------------------------------------

WDIR=`pwd`

SIESTA_BIN=${SIESTA_BIN:=../Util}

if [ $# -lt 2 ] ; then
      echo "qrrsiesta: Usage: qrrsiesta name queue [init]"
      exit 1
fi
init=""
if [ $# -eq 3  -a "$3" = "init" ] ; then
      init=$3
fi
#
name=$1
if [ ! -r $name.fdf ] ; then
      echo "qrrsiesta: Cannot read $name.fdf"
      exit 1
fi
if [ -r $name.out ] ; then
      echo "qsiesta: Old $name.out being moved to $name.out.old"
      mv -f $name.out $name.out.old
fi
#
queue=$2
#
qsub -q $queue -eo -o $name.qlog -r $name <<EOF
export PATH=${SIESTA_BIN}:${WDIR}:${PATH}
cd $WDIR
rrsiesta $name $init
EOF
#







