#!/bin/sh
#-------------------------------------------------------------
# Queues (submits) a job to run the SIESTA program, assuming
# it is already compiled and resides somewhere in the user's path.
#
# Syntax:  qsiesta name queue
# Example: qsiesta H2O express 
#
# SIESTA output goes to name.out, and complete log file to name.qlog
#
# Environment variable $SIESTA_DIR should be previously defined.
# If it is not defined, it assumes SIESTA_DIR = ../siesta/Src
#
# Environment variable $SIESTA_BIN can be defined to locate
# the utility scripts called by this one (prdate).
# If it is not defined, it assumes SIESTA_BIN = ../siesta/Util
#
# Data file name.fdf must exist in working directory.
#
# Written by J.M.Soler. August 1997.
# Modified by Alberto Garcia, March 1998.
#-------------------------------------------------------------

WDIR=`pwd`

SIESTA_BIN=${SIESTA_BIN:=../siesta/Util}

if [ $# -ne 2 ] ; then
      echo "qsiesta: Usage: qsiesta name queue"
      exit 1
fi
#
name=$1
if [ ! -r $name.fdf ] ; then
      echo "qsiesta: Cannot read $name.fdf"
      exit 1
fi
if [ -r $name.out ] ; then
      echo "qsiesta: Old $name.out being moved to $name.out.old"
      mv -f $name.out $name.out.old
fi
#
queue=$2
#
qsub -q $queue -eo -o $name.qlog -r $name <<EOF
export PATH=${SIESTA_BIN}:${WDIR}:${PATH}
cd $WDIR
prdate siesta | tee $name.out
siesta < $name.fdf >> $name.out
prdate siesta | tee -a $name.out
EOF
#

