#!/bin/sh 
#-------------------------------------------------------------
# 'Really' runs the SIESTA program, recompiling until it runs.
# Syntax:  rrsiesta name [init|touch]
# Example: rrsiesta H2O
#
# If the 'init' option is specified, the default .h parameter files
# in SIESTA_DIR/Include are used (good for first compilation).
#
# If the 'touch' option is specified, the .h parameter files
# located in the working (project) directory are 'touched' and copied
# to the source directory. In this way the parameter information garnered
# in previous compilations can be reused even if other, unrelated, 
# compilation cycles have 'corrupted' the source directory.
#
# Environment variable $SIESTA_DIR should be previously defined,
# If it is not defined, it assumes SIESTA_DIR = ../siesta/Src
#
# Data file name.fdf must exist in working directory.
#
# Original version written by J.M.Soler. August 1997.
#
#-------------------------------------------------------------

if [ $# -gt 1 -a "$2" = init ] ; then
  msiesta init
else
  if [ $# -gt 1 -a "$2" = touch ] ; then
    msiesta touch
  else
    msiesta
  fi
fi

rsiesta $1

while grep RECOMPILE $1.out > /dev/null ; do 
  msiesta
  rsiesta $1
done


