#!/bin/sh 
#-------------------------------------------------------------
# Runs the SIESTA program.
# Syntax:  rsiesta name
# Example: rsiesta H2O
#
# Environment variable $SIESTA_DIR should be previously defined,
# If it is not defined, it assumes SIESTA_DIR = ../siesta/Src
#
# Data file name.fdf must exist in working directory.
# Written by J.M.Soler. August 1997.
# Modified by Alberto Garcia. March 1998.
#-------------------------------------------------------------

SIESTA_DIR=${SIESTA_DIR:=../siesta/Src}

if [ $# -ne 1 ] ; then
      echo "rsiesta: Usage: rsiesta jobname"
      exit 1
fi

if [ ! -r $1.fdf ] ; then
      echo "rsiesta: Cannot read $1.fdf"
      exit 1
fi

prdate siesta | tee $1.out

if [ ! -x siesta ] ; then
	echo "Compiling siesta..."
	msiesta
fi

siesta < $1.fdf | tee -a $1.out 

if  egrep 'ERROR|WARNING' $1.out > /dev/null ; then
  echo " " | tee -a $1.out
  echo "rsiesta: Run-time errors and warnings:" | tee -a $1.out
  egrep 'ERROR|WARNING' $1.out | tee -a $1.out
  echo " " | tee -a $1.out
fi

prdate siesta | tee -a $1.out


