
subroutine initSwan(ispin,systemName)
  use nnkp
!***************************************** init Swan *******************
! Feeds the following private module variables:
! nnCount, numKPoints, nnList, nnFolding, kPointsFrac, latVec,
! recLatVec,  nnkpDateAndTime, projections, isExcluded
! by reading the .nnkp file generated by the Wannier 90 preprocessor.
! Allocates dynamic variables
!***********************************************************************

  integer,intent(in)        :: ispin
  character(*),intent(in)   :: systemName
  integer                   :: eof
! dimension iterator
  integer                   :: i
!
  integer                   :: nnkpUnit
! file names
  character(len=len_trim(systemName)+5):: nnkpFileName
! indices, iterators
  integer                   :: inn,iterEx,band
! list of excluded bands as given in nnkp
  integer,pointer           :: excludedBands(:)

ensubroutine initSwan
