C $Id: iorder.f,v 1.2 1999/01/31 11:14:57 emilio Exp $

      SUBROUTINE IORDER( IA, M, N, INDEX )
C *******************************************************************
C Orders integer array IA(M,N) according to array INDEX(N), which
C   may be generated by routine ORDIX.
C Written by J.M.Soler. May'96 and Oct'97.
C *************** INPUT *********************************************
C INTEGER M, N     : Dimensions of array IA
C INTEGER INDEX(N) : Array which gives the desired order
C *************** INPUT AND OUTPUT **********************************
C REAL*8  IA(M,N): Array(s) to be ordered: IAout(I,J) = IAin(I,INDEX(J))
C *******************************************************************
      IMPLICIT NONE
      INTEGER  M, N
      INTEGER  IA(M,N), INDEX(N)

      INTEGER  I, IAI, IORD, ISTORE, J

      DO 40 J = 1,M
        DO 20 I = 1,N
          IAI = IA(J,I)
          IORD = I
   10     CONTINUE
          ISTORE = INDEX(IORD)
          IF (ISTORE .GT. 0) THEN
            IF (ISTORE .EQ. I) THEN
              IA(J,IORD) = IAI
            ELSE
              IA(J,IORD) = IA(J,ISTORE)
            ENDIF
            INDEX(IORD) = -INDEX(IORD)
            IORD = ISTORE
            GOTO 10
          ENDIF
   20   CONTINUE
        DO 30 I = 1,N
          INDEX(I) = -INDEX(I)
   30   CONTINUE
   40 CONTINUE
      END

